// src/config.ts — All tunable game constants. No magic numbers in game logic.
export const GAME_CONFIG = {
  STARTING_SANITY: 100,
  FOCUS_MODE_DURATION_MS: 25_000,
  FOCUS_MODE_COOLDOWN_MS: 45_000,
  FOCUS_MODE_SANITY_RECOVERY: 5,
  CONTEXT_SWITCH_WINDOW_MS: 5_000,
  CONTEXT_SWITCH_THRESHOLD: 3,
  CONTEXT_SWITCH_PENALTY_SANITY: 2.0,
  CONTEXT_SWITCH_OVERLAY_MS: 1_500,
  DEFER_ESCALATION_MULTIPLIER: 1.5,
  SLACK_STORM_COUNT: { min: 8, max: 12 },
  ALL_HANDS_WINDOW_GAME_MINUTES: { start: 120, end: 180 }, // 10–11 AM
  GOAL_GRADIENT_THRESHOLD_REAL_S: 20,   // 20s before 5 PM
  GOAL_GRADIENT_SPAWN_REDUCTION: 0.20,
  SANITY_CRITICAL_THRESHOLD: 30,
  SANITY_HEARTBEAT_THRESHOLD: 15,
  TOTAL_REAL_DURATION_MS: 180_000,
  CANVAS: { width: 414, height: 896 },   // iPhone 14 Pro portrait baseline
} as const;
